# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  pr:
    required: false
  image_tag:
    required: false
  organization_id:
    required: false
  location:
    required: true
outputs:
  deployment:
    description: "The Cloud deployment associated with this branch."
runs:
  using: 'docker'
  image: 'public.ecr.aws/a6x1l7i5/gh-action-test:0.2'
  # image: '../Dockerfile'
  entrypoint: '/deploy.sh'
  args:
    - ${{ inputs.pr }}
